### ISSUE TITLE
Sanguine Global Config

### ISSUE THREAD

**Issue by nautsimon** [synapsecns/sanguine#1586]
# Sanguine Global Config

One of the biggest pain points in onboarding tokens and chains is duplicating data across all of the different frontends and services in Sanguine. Putting all token and chain data in a single config file in Sanguine would make onboarding/editing tokens easier, contribute to codebase maintainability, and help any other builders using our sdk or services. 
<br/>
I will outline some idea of how this could be accomplished, first, here is a list of the services and packages that currently rely on some sort of token/chain config (as you can see, maintaining uniformity between these modules is a bit tedious).
- `packages/synapse-interface`
- `packages/sdk-router`
- `packages/rest-api`
- `packages/explorer-ui`
- `services/explorer`

## Implementation
I propose that we create 2 yaml files (yaml for uniformity across other configs), one for chains and one for tokens, in a new directory `/static`. Most of this task is parsing data from the explorer constants files `/packages/synapse-interface/constants` into yaml. Then, GitHub workflows that can convert these configs into the format needed by all dependent packages will need to be written. 

### Chain config requirements
```
id (int)
- id: number
- chainSymbol: string
- name: string
- altName?: string
- codeName: string
- chainImg: any
- layer: number
- rpcUrls: { primary: string; fallback: string }
- explorerUrl: string
- explorerName: string
- explorerImg: any
- blockTime: number
- nativeCurrency: { name: string; symbol: string; decimals: number }
- priorityRank?: number
- color?: string
```

### Token config requirements 
This is essentially a 1:1 to the synapse-interface [Token class](https://github.com/synapsecns/sanguine/blob/c180c770ad8b2c2180bce5e841d4ea66f21d16b6/packages/synapse-interface/utils/types/index.tsx#L123) 
```
name
- addresses: { [x: number]: string } // list of token addresses on each chain
- wrapperAddresses: Record<number, string> // list of wrapper addresses on each chain like gmx
- decimals: number | Record<number, number> = {} // list of decimals on each chain
- symbol?: string // token symbol
- name?: string // token name
- logo?: any // token logo
- icon?: any // token icon
- poolName?: string // token pool name
- swapAddresses?: Record<number, string> // list of swap addresses on each chain
- swapWrapperAddresses?: Record<number, string> // list of swap wrapper addresses on each chain
- swapDepositAddresses?: Record<number, string> // list of swap deposit addresses on each chain
- swapEthAddresses?: Record<number, string> // list of swap eth addresses on each chain
- routerIndex?: string // router index
- poolId: number | Record<number, number> = {} // list of pool ids on each chain
- poolType?: string // pool type
- poolTokens?: Token[] // list of pool tokens
- depositTokens?: Token[] // list of deposit tokens
- nativeTokens?: Token[] // list of native tokens
- description?: string // token description
- docUrl = '' // token doc url
- forceMeta?: boolean // force meta
- swapableType?: string // swappable type
- isNative = false // is native
- swapExceptions: number | Record<number, number[]> = {} // for specifying tokens where limited dest chains are available.
- visibilityRank = 0 // rank in which token is displayed, least visible is 0, there is no max
- isMeta = false // is meta
- isEthSwap = false // is eth swap
- category: { bridge: boolean; swap: boolean; pool: boolean } = {
    bridge: true,
    swap: true,
    pool: true,
  } // list of categories on each chain
- swapableOn: number[] = [] // list of chains where token is swapable
- display = true // display token
- legacy = false // legacy token
- priorityRank: number // priority token ordering
- chainId?: number // chain id of swap pool
- incentivized?: boolean // pool is incentivized or not
- customRewardToken?: string // reward token symbol when pool staking rewards are in something other than SYN
- miniChefAddress: string // mini chef address
- priorityPool?: boolean = false // priority pool
- color?:
    | 'gray'
    | 'yellow'
    | 'green'
    | 'lime'
    | 'sky'
    | 'blue'
    | 'orange'
    | 'purple'
    | 'indigo'
    | 'cyan'
    | 'red'
- priceUnits?: string
- notStake?: boolean
- routeSymbol?: string
- coingeckoID (string)
- type (string) // Which config file from the `synapse-interface/constants/tokens` is this token from (eg. bridegable, swap, etc.). This will help with parsing.
- logoPath (string) // Use this to create the import statement at the top of the typescript file
- iconPath (string) // Use this to create the import statement at the top of the typescript file
```

### Scripts and Github Workflows
These configs alone will not really do anything. To make these useful there needs to be a couple scripts that convert these configs into the ts files used by the various packages in their `/constants` directories. This part might be a bit tedious but will save unnecessary refactoring on all the packages. Im going to break this down into each of the files that need to be written. 

**[Updater Script]**
  A script that takes the token and chain yaml config and parses it into all the constants files in `/packages`. 
  Here are the files that will need to be re-created by this script from the yaml
  - [synapse-interface bridgeable token config](https://github.com/synapsecns/sanguine/blob/master/packages/synapse-interface/constants/tokens/bridgeable.ts)
  - [synapse-interface pool token config](https://github.com/synapsecns/sanguine/blob/master/packages/synapse-interface/constants/tokens/poolMaster.ts)
  - [synapse-interface auxiliary token config](https://github.com/synapsecns/sanguine/blob/master/packages/synapse-interface/constants/tokens/auxilliary.ts)
  - [synapse-interface sushi token config](https://github.com/synapsecns/sanguine/blob/master/packages/synapse-interface/constants/tokens/sushiMaster.ts)
  - [synapse-interface swap token config](https://github.com/synapsecns/sanguine/blob/master/packages/synapse-interface/constants/tokens/swapMaster.ts)
  - [synapse-interface chain config](https://github.com/synapsecns/sanguine/blob/master/packages/synapse-interface/constants/chains/master.tsx)
  - [sdk-router chain ids](https://github.com/synapsecns/sanguine/blob/master/packages/sdk-router/src/constants/chainIds.ts)
  - [rest-api chains](https://github.com/synapsecns/sanguine/blob/master/packages/rest-api/src/config/chains.json)
  - [rest-api tokens](https://github.com/synapsecns/sanguine/blob/master/packages/rest-api/src/config/tokens.json)

  Notes
  - The easiest thing to do for parsing the tokens for the interface and explorer is probably writing a js file that takes the yamls and implementing the constructor of the synapse-interface [Token class](https://github.com/synapsecns/sanguine/blob/c180c770ad8b2c2180bce5e841d4ea66f21d16b6/packages/synapse-interface/utils/types/index.tsx#L123) in the parser (for doing the token constants in packages/synapse-interface and packages/explorer-ui). 
  - Ensure that you are also generating the imports as well (get the path from the yaml config).

**[Test Script]**
  A script that is essentially the Updater Script but just runs the parsing logic and checks for errors (does not generate files).

**[Github Workflow (Run Test Script)]**
  - Will run in a PR when any changes to `/static` are made, will run the test scripts to make sure the changes are valid.

**[Github Workflow (Run Updater Script)]**
  - Needs to execute the scripts when any changes to `/static` are made and pushed to master. 
  - Will open PRs with the changes from the scripts for each package. In `explorer-ui` and `synapse-interface` check to see for any missing assets for each token and chain (check the path from the config). If there are any missing assets, append a warning, the token/chain name, and the expected path to the PR description.

## Execution
1. Parse the constants from `/packages/synapse-interface/constants` into yaml files + fill out all the fields
2. Create GitHub workflow + script that generate the required configs in the packages in `/packages` and creates PRs for each one once changes are merged to master.
3. Add GitHub workflow that runs the test script.
4. Update explorer to import the config.
5. Explorer-ui constants scheme needs to be updated/refactored from the one of the ui to that of the new ui. Then the same generate scripts for the interface can than be used for the explorer ui (just added the `explorer-ui/constants` as an additional target).

## Some other ideas
- Incorporate the "bridgeablity" script into the scripts
- Have the config hosted on a CDN somewhere and have all the services pull the json file from there on load (pros: no generating and redeploying on edits, cons: arguably insecure)
- We could probably make all this parsing easier if the interface was refactored to load from yaml (this would change the way images are loaded). Not sure if the upside for doing this is worth.

## Notes
- Scripts will not have to generate anything in `/services`, they will just import the `/static` module.
- Add ideas!

**Comment by trajan0x** [comment]
Fixed by synapse-constants basically
