### ISSUE TITLE
Ignore Generated Files in Coderabbit

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#2237]
See [here](https://github.com/synapsecns/sanguine/pull/2236#discussion_r1518470978) for an example of what should be ignored. Also `.golangci.yml`

**Comment by shashank40** [comment]
Hey @trajan0x can i pick this up?
Also is this not a part of bounty system?

**Comment by trajan0x** [comment]
nah it's not @shashank40. but I can try and find an issue for you if interested. This was already done #2244 so gonna close but lmk if you're interested

**Comment by shashank40** [comment]
Yes @trajan0x i am interested. Would love to fix a bunch of issues that might help the team.

**Comment by shashank40** [comment]
Hey @trajan0x , any update?
