### ISSUE TITLE
Enhance Revert Reasoning with RevertResolver Integration and Global Contract Registration

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#2318]
**Context**

The \`RevertResolver\` tool, located in [\`/tools/revertresolver/main.go\`](https://github.com/synapsecns/sanguine/blob/master/tools/revertresolver/main.go), provides crucial functionality for decoding revert reasons in Ethereum smart contracts. The current implementation in [\`ethergo/backends/base/base.go\` at line 230](https://github.com/synapsecns/sanguine/blob/master/ethergo/backends/base/base.go#L230) handles transaction rejections but lacks the mechanism to print detailed revert reasons, which is essential for effective debugging.

**Proposal**

I propose to integrate the \`RevertResolver\` into the \`ethergo/backends/base\` package to automatically decode and display revert reasons upon transaction failures. Additionally, I suggest implementing a global contract store mechanism to dynamically register contracts and use this registry to resolve revert reasons efficiently.

**Integration Steps**

1. **Incorporate RevertResolver Module**: Add the \`RevertResolver\` module to the \`ethergo/backends\` package to ensure it's accessible for decoding revert reasons.

2. **Implement RegisterContract Method**: Introduce a \`RegisterContract\` method to add contracts to a global contract store. This store will maintain references to all registered contracts, facilitating the resolution of revert reasons based on contract addresses.

3. **Resolve Reverts Using Global Store**: Utilize the global contract store within the transaction handling process to decode and print revert reasons. When a transaction fails, the system should consult the global store to find the corresponding contract and use \`RevertResolver\` to decode the revert reason.

**Metadata Template Modification for Global Hook Registration**

To support the dynamic registration of contracts and the efficient resolution of revert reasons, the metadata template in [\`tools/abigen/internal/generate.go\` at line 229](https://github.com/synapsecns/sanguine/blob/master/tools/abigen/internal/generate.go#L229) requires modification. The template should be enhanced to include hooks for the global contract registration, enabling automated tracking and resolution of revert reasons across all registered contracts.

**Suggested Approach for Metadata Template Modification**

1. **Template Adjustment**: Amend the code generation template to include a registration hook within the contract initialization logic. This hook should call the \`RegisterContract\` method with the contract's address and ABI, ensuring it's added to the global contract store.

2. **Registration Hook Implementation**: Develop the registration hook logic within the contract initialization code, ensuring that each deployed contract is automatically registered in the global store upon creation or first use.

3. **Documentation & Testing**: Update documentation to explain the registration process and the benefits of the global contract store for revert reason resolution. Provide comprehensive tests to validate the registration mechanism and the enhanced revert reason decoding functionality.

**Benefits**

This integration will not only facilitate more intuitive debugging by providing clear revert reasons but also establish a robust mechanism for contract management and revert resolution through a global contract store.

**Request for Comments**

Feedback and suggestions from the community on this proposal are highly welcomed. Discussions around technical implementation, potential improvements, and any overlooked aspects are particularly encouraged.

**Comment by shashank40** [comment]
Can you please assign it to me @trajan0x 
/attempt #2318

**Comment by trajan0x** [comment]
@shashank40 assigned. Let me know if you have a timeline/what you're thinking for the attempt

**Comment by shashank40** [comment]
I will just take a day to analyse the problem and give a timeline @trajan0x

**Comment by trajan0x** [comment]
Assuming this is abandoned
