### ISSUE TITLE
Print TX Hash from Withdrawals

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#2835]
Add on for #2815

 - Requires adding an optional api to submitter, should return a Handler (you can see an example of this [here]()
 - https://pkg.go.dev/github.com/synapsecns/sanguine/core/metrics#section-readme (see `Gin()` and how it's used, particularly in `contrib/promexporter`) 
 - Configure this api to start at boot up in `relapi/server.go` and return `GetNonceStatus` for a given nonce as json
 - Write a client for this submitter api, attach the client to the rfq api client (`relapi/client.go`)
 - From the CLI call this on a loop until we get the txhash, consider using `github.com/charmbracelet/huh/spinner` for this (see an example [here](https://github.com/synapsecns/sanguine/blob/9cdc208d87ac3128841cc2e2a7ba7454860496b5/contrib/opbot/signoz/example/main.go#L9): this part is purely optional

**Comment by golangisfun123** [comment]
resolved in #2845
