### ISSUE TITLE
Wait for Finality before posting Prove TX

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#3056]
In the current implementation of relayer, the following can happen (all relays/proves are assumed to be for same bridge request):

1. Relayer A calls `relay()`, which succeeds
2. Relayer B calls `relay()`, which reverts on account of relayer A already submitting tx
3. Relayer A, seeing their relay succeeded calls `prove()`
4. The chain where `relay()` is called re-orgs and Relayer B's tx is put before Relayer A's making Relayer A guilty of submitting a false prove

You can solve this by calling eth_getTransactionByReceipt and waiting for "safe" before posting prove

Guard should also consider finality by waiting a few blocks back when listening

**Comment by dwasse** [comment]
Addressed here: https://github.com/synapsecns/sanguine/pull/3062
