### ISSUE TITLE
Design and implement proper synchronization of Bonding Managers

### ISSUE THREAD

**Issue by ChiTimesChi** [synapsecns/sanguine#326]
#316 implements the MVP for Bonding Managers, contracts that are responsible for syncing the information about the off-chain actors, who have committed their staking bond on Synapse Chain.

## Why do we need that?

The actions tied to bonding, and especially unbonding, require the confirmation that the new piece of information has been successfully passed to all relevant domains. For example, if an off-chain agent wants to unstake their bond, we need to do both:

- Send information that the agent is no longer active to all chains, where this actor signature is valid.
- Receive confirmation from all such chains that the actor is removed.

Only after both are completed, the staking bond could be unlocked.

## Information to sync

1. A new Notary/Guard staked a bond. Originates on Synapse Chain, need to inform all other chains.
2. An active Notary/Guard initiates the unbonding. Originates on Synapse Chain, need to inform all other chains.
3. An active Notary/Guard was slashed. Originates on any chain, should be forwarded to Synapse Chain first. Then to all the remaining chains.
  > The incentives should be structured in a way, where the slashed actor will have been reported already (assuming rational actors) by the time the information about slashing is finally forwarded.

## Considerations

1. Implementation should resemble a ping-pong scheme:
  a. First, `BondingPrimary` on Synapse Chain forwards new information to all the `BondingSecondary` contracts (pings).
  b. `BondingSecondary` responds with a pong upon handling the information.
  c. `BondingPrimary` should ensure that number of received pongs is equal to number of sent pings.
2. What happens if one of the pongs gets delayed? Due to contract error, or simply due to the destination domain being halted?
3. Do we need some kind of timeout mechanism to prevent deadlocks?
4. Do we need to send a new wave of pings once all the pongs are received? So that every `BondingSecondary` knows that the new piece of information is synced everywhere.
5. Do we need to bulk the synchronization process? For example, send information about all updated agents statuses at most once per day (or once there's at least `N` status changes to prevent out-of-gas DoS attacks).

**Comment by trajan0x** [comment]
Closing for now, can re-open later if relevant
